name: flutter_news_cast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  get: 4.6.6
  sprintf: ^7.0.0
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  logger: ^2.0.2+1
  firebase_messaging: ^14.7.17
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  flutter_local_notifications: ^16.3.2
  wakelock_plus: ^1.1.4
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.4
  event_bus: ^2.0.0
  connecteo: ^2.2.0
  url_launcher: ^6.2.5
  flutter_cupertino_datetime_picker: ^3.0.0
  #Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.2
  #Rss
  dart_rss: ^3.0.2
  flutter_displaymode: ^0.6.0
  flutter_inappwebview: ^6.0.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

dependency_overrides:
  intl: ^0.19.0

flutter_gen:
  output: lib/res/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/