name: flutter_news_cast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  get: 4.6.6
  sprintf: ^7.0.0
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  logger: ^2.0.2+1
  firebase_messaging: ^14.7.17
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  flutter_local_notifications: ^16.3.2
  wakelock_plus: ^1.1.4
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.4
  event_bus: ^2.0.0
  connecteo: ^2.2.0
  url_launcher: ^6.2.5
  flutter_cupertino_datetime_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/res/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 500
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800
        - asset: assets/fonts/Muli-ExtraBold.ttf
          weight: 900
    - family: SfPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
  assets:
    - assets/json/
    - assets/icons/
    - assets/icons/login/
    - assets/icons/menu/
    - assets/icons/info/
    - assets/icons/home/
    - assets/icons/icon_bank/
    - assets/icons/qrcode/
    - assets/icons/notification/
    - assets/icons/payment/
    - assets/icons/logo/
    - assets/images/
    - assets/images/home/
    - assets/images/payment/