name: flutter_news_cast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: 4.6.5
  sprintf: ^7.0.0
  dio: ^5.3.4
  intl: ^0.18.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.3.0
  logger: ^2.0.2
  lottie: ^2.7.0
  pin_code_fields: ^8.0.1
  device_info_plus: ^9.1.1
  fluttertoast: ^8.2.4
  flutter_local_notifications: ^16.3.2
  pattern_formatter: ^3.0.0
  custom_clippers: ^2.0.0
  dotted_line: ^3.2.2
  spelling_number: ^0.0.4
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/res/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 500
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800
        - asset: assets/fonts/Muli-ExtraBold.ttf
          weight: 900
    - family: SfPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
  assets:
    - assets/json/
    - assets/icons/
    - assets/icons/login/
    - assets/icons/menu/
    - assets/icons/info/
    - assets/icons/home/
    - assets/icons/icon_bank/
    - assets/icons/qrcode/
    - assets/icons/notification/
    - assets/icons/payment/
    - assets/icons/logo/
    - assets/images/
    - assets/images/home/
    - assets/images/payment/